name: ActionsDemo main.yml
on: # workflow 触发事件
  push:
    branches: 
      - master
    paths:
      - src/*
jobs: # 任务集
  build-deploy: # 自定义 job_id
    container: 
      image: node:latest # 进入容器 steps run in bash/shell
    steps: # 步骤集
      - name: git clone && git config && node server.js && git push
        run: |
          git clone https://${{ secrets.REST_TOKEN }}@github.com/unkwninfo/ActionsDemo.git
          git config --global user.name "unkwninfo"
          git config --global user.email "unkwninfo@gmail.com"
          cd ActionsDemo
          node server.js
          git add -A
          git commit -m "Actions src/* => docs/*"
          git push
