name: ActionsDemo main.yml
on: # workflow 触发事件 <must>
  push:
    branches: 
      - master
    paths:
      - src/*
jobs: # 任务集 <must>
  build-deploy: # 自定义 job_id <must>
    runs-on: ubuntu-latest # 虚拟机环境 <must>
    # container: 
    #  image: node:latest # 进入容器 steps run in bash/shell
    steps: # 步骤集 <must>
      - name: git clone && git config && node server.js && git push
        run: | # CLI <must>
          git config --global user.name "unkwninfo"
          git config --global user.email "unkwninfo@gmail.com"
          git clone https://${{ secrets.REST_TOKEN }}@github.com/${{ github.repository }}.git ${{ github.workspace }}
          node server.js
          git add -A
          git commit -m "Actions src/* => docs/*"
          git push
