name: README.log

on:
  push:
    branches: 
      - master
    paths:
      - src/*

jobs:
  log:
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        node -v
        pwd
