name: README.log

# event 事件
on:
  push:
    branches: 
      - master
    paths:
      - src/*

jobs:
  # job_id 自定义
  log:
    # 工作环境
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    # 步骤
    steps:
      # pull codes
      # - uses: actions/checkout@v2
      - run: |
          git clone https://unkwninfo:${{ secrets.REST_TOKEN }}@github.com/unkwninfo/ActionsDemo.git
          git config --global user.name "unkwninfo"
          git config --global user.email "unkwninfo@gmail.com"
      # shell command
      - run: |
          node server.js
          git add -A
          git commit -m "Actions src/* => docs/*"
          git push
