name: README.log

# event 事件
on:
  push:
    branches: 
      - master
    paths:
      - src/*

jobs:
  # job_id 自定义
  log:
    # 工作环境
    runs-on: ubuntu-latest
    container: 
      image: node:latest
    # 步骤
    steps:
      # pull codes
      - uses: actions/checkout@v2
      # shell command
      - run: |
          node -v
          pwd
          ls -al
          node server.js
          git add .
          git commit -m 'update src/*'
          git push
