name: Test CI
on:
  push:
    branches: 
      - master
    paths:
      - .github/workflows/test.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test Step
      run: |
        pwd
        sudo apt install tree
        git config -l
        cd ..
        git clone https://${{ github.token }}@github.com/${{ github.repository }}.git
        git config --global user.name "unkwninfo"
        git config --global user.email "unkwninfo@gmail.com"
        tree -a
        pwd
        date >> ${{ github.workspace }}/src/log
        git add -A
        git commit -m "update src/log +date"
        git push
